// Colores para el selector de partidos (vista nacional/departamental).
// Editar aquí para cambiar el color con que se resalta cada partido en el mapa y el selector.
// Dejar en '' para que se genere automáticamente.
// Estos colores son independientes de los colores de leyenda por municipio (que vienen del CSV).
const PARTY_COLORS = {
    'A-UPP': '',
    'A.S.': '',
    'AAGP': '',
    'AGN': '',
    'AIR': '',
    'AORA': '',
    'APB-SUMATE': '',
    'APP': '',
    'ASLP': '',
    'ASP': '',
    'CAMPO': '',
    'CAOP': '',
    'CAOSAM': '',
    'CDC': '',
    'CONACH-W': '',
    'CREEMOS': '',
    'DEMOCRATAS': '',
    'DESPIERTA': '',
    'F.S.D.': '',
    'FE': '',
    'FRI': '',
    'GH': '',
    'IH': '',
    'JACHAJAKISASOLFESORC': '',
    'JALLALLA LP': '',
    'LIBRE': '',
    'LIBRE-PANDO': '',
    'M.P.S.': '',
    'MACOJMA': '',
    'MDA': '',
    'MNR': '',
    'MTS': '',
    'NGP': '',
    'P.P.': '',
    'PDC': '',
    'PODER-O': '',
    'POKUY': '',
    'PPS': '',
    'PSC': '',
    'Patria': '#eb8c34',
    'SOLUCIONES-CON-TODOS': '',
    'SOMOS': '',
    'SPBC': '',
    'SPT': '',
    'SW': '',
    'T': '',
    'T.S.': '',
    'TODOS-': '',
    'TU': '',
    'TUFE': '',
    'UN': '',
    'UNIDOS': '',
    'UNIDOS-': '',
    'UPC': '',
    'UPP': '',
    'VENCEREMOS': '',
    'VIDA': '',
    'VOS': '',
    'XS-CH': '',
};
